import hashlib
import subprocess
from pathlib import Path
from subprocess import check_output
from tempfile import TemporaryDirectory

from chardet import detect

VENDOR_DIR = Path(__file__).parent.parent / "pyswot" / "vendor"


def clone_repo(
    *, target_dir: Path, repo: str = "https://github.com/JetBrains/swot.git"
) -> str:
    check_output(["git", "clone", "--depth", "1", repo, target_dir])
    process = check_output(
        ["git", "rev-parse", "--short", "HEAD"], cwd=target_dir
    )
    return f"{repo}@{process.decode('utf-8')}"


def create_set(
    *,
    src: Path,
    dest: Path,
    varname: str,
    commit_id: str,
    extra: set[str] | None = None,
) -> None:
    with open(src) as f:
        var = {v for v in f.read().splitlines() if v}

    if extra is not None:
        var.update(extra)

    with open(dest, "w") as f:
        f.write(
            "# DO NOT EDIT THIS FILE, "
            f"CHANGES WILL BE OVERWRITTEN BY {Path(__file__).name}\n"
        )
        f.write(f"# From {commit_id}\n")
        f.write(f"{varname} = frozenset({repr(sorted([*var]))})\n")


def _get_key(*, rel_path: Path) -> str:
    parts = list(rel_path.parts)

    # Strip txt
    parts[-1] = parts[-1][:-4]
    parts.reverse()

    return "." + ".".join(parts)


def create_dict(
    *, src: Path, dest: Path, varname: str, commit_id: str
) -> None:
    var = {}
    domains = sorted(src.rglob("*.txt"))

    for domain in domains:
        if domain.parent == src:
            # Skip files in the top level directory
            continue

        with open(domain, "rb") as f:
            lines = f.read().splitlines()

        school_info = []
        for line in lines:
            if line:
                try:
                    i = line.decode("utf-8")
                except UnicodeDecodeError:
                    encoding = detect(line)["encoding"]
                    i = line.decode(encoding)
                school_info.append(i)

        var[_get_key(rel_path=domain.relative_to(src))] = school_info

    with open(dest, "w") as f:
        f.write(
            "# DO NOT EDIT THIS FILE, "
            f"CHANGES WILL BE OVERWRITTEN BY {Path(__file__).name}\n"
        )
        f.write(f"# From {commit_id}\n")
        f.write(f"{varname}: dict[str, list[str]] = {repr(var)}\n")


def calculate_sha256(filename: Path) -> str:
    sha256_hash = hashlib.sha256()

    with open(filename, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            sha256_hash.update(chunk)

    return sha256_hash.hexdigest()


def main() -> int:
    with TemporaryDirectory() as tmp_dir:
        tmp_path = Path(tmp_dir)

        commit_id = clone_repo(target_dir=tmp_path)
        create_set(
            src=tmp_path / "lib" / "domains" / "stoplist.txt",
            dest=VENDOR_DIR / "stoplist.py",
            varname="STOPLIST",
            commit_id=commit_id,
            extra={"edu.kg", "mona.edu.pl", "edumail.edu.pl"},
        )
        create_set(
            src=tmp_path / "lib" / "domains" / "tlds.txt",
            dest=VENDOR_DIR / "tlds.py",
            varname="TLDS",
            commit_id=commit_id,
        )
        create_dict(
            src=tmp_path / "lib" / "domains",
            dest=VENDOR_DIR / "domains.py",
            varname="DOMAINS",
            commit_id=commit_id,
        )

        free_domains_file = tmp_path / "free-domains.csv"

        # Source free domains from
        # https://knowledge.hubspot.com/forms/what-domains-are-blocked-when-using-the-forms-email-domains-to-block-feature
        subprocess.run(
            [
                "wget",
                f"--output-document={free_domains_file}",
                "https://f.hubspotusercontent40.net/hubfs/2832391/Marketing/Lead-Capture/free-domains-2.csv",
            ],
            check=True,
            capture_output=True,
        )

        free_domains_hash = calculate_sha256(free_domains_file)

        create_set(
            src=free_domains_file,
            dest=VENDOR_DIR / "free.py",
            varname="FREE",
            commit_id=free_domains_hash,
            extra={
                "pm.me",
                "proton.me",
                "protonmail.ch",
            },
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
