name: Update Vendor Sources

on:
  schedule:
    - cron: '42 5 * * 1'
  workflow_dispatch:

env:
  MINIMUM_PYTHON_VERSION: "3.10"

jobs:
  sync:
    name: Update Vendor Sources
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.DEPENDENCY_UPDATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.DEPENDENCY_UPDATE_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}

      - name: Update Vendor Sources
        run: uv run python ./scripts/update_vendor.py

      - name: Bump patch version
        run: uv run python ./scripts/bump_version.py

      - name: Run black
        run: uv run black .

      - name: Run pre-commit
        run: uv run pre-commit run -a
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Automated vendor update"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch-suffix: "short-commit-hash"
          delete-branch: true
          title: "Automated vendor update"
          body: ""
